---
title: "Homework 5"
author: "[Jingchun Zhang]{style='background-color: yellow;'}"
toc: true
title-block-banner: true
title-block-style: default
execute: 
  freeze: true
  cache: true
format:
  html: # comment this line to get pdf
  # pdf: 
    fig-width: 7
    fig-height: 7
---


---

::: {.callout-important style="font-size: 0.8em;"}

Please read the instructions carefully before submitting your assignment.

1. This assignment requires you to only upload a `PDF` file on Canvas
1. Don't collapse any code cells before submitting. 
1. Remember to make sure all your code output is rendered properly before uploading your submission.

⚠️ Please add your name to the author information in the frontmatter before submitting your assignment ⚠️
:::


In this assignment, we will explore decision trees, support vector machines and neural networks for classification and regression. The assignment is designed to test your ability to fit and analyze these models with different configurations and compare their performance.

We will need the following packages:


```{R, message=FALSE, warning=FALSE, results='hide'}
#rm(list=ls())
packages <- c(
  "tibble",
  "dplyr", 
  "readr", 
  "tidyr", 
  "purrr", 
  "broom",
  "magrittr",
  "corrplot",
  "caret",
  "rpart",
  "rpart.plot",
  "e1071",
  "torch", 
  "luz"
)

# renv::install(packages)
sapply(packages, require, character.only=T)
```

<br><br><br><br>
---

## Question 1
::: {.callout-tip}
## 60 points
Prediction of Median House prices
:::

###### 1.1 (2.5 points)


The `data` folder contains the `housing.csv` dataset which contains housing prices in California from the 1990 California census. The objective is to predict the median house price for California districts based on various features.


Read the data file as a tibble in R. Preprocess the data such that:

1. the variables are of the right data type, e.g., categorical variables are encoded as factors
2. all column names to lower case for consistency
3. Any observations with missing values are dropped

```R
path <- "data/housing.csv"

df <- ... # Insert your code here
```
```{R}

path <- "/Users/zhangjingchun/Desktop/STAT380/housing.csv"
df <- read_csv(path)

names(df) <- tolower(names(df))

df <- df %>%
  mutate(ocean_proximity = as.factor(ocean_proximity))

df <- drop_na(df)
print(head(df))

```


---

###### 1.2 (2.5 points)

Visualize the correlation matrix of all numeric columns in `df` using `corrplot()`

```R
df %>% ... # Insert your code here
```
```{R}
library(dplyr)
library(corrplot)

numeric_data <- df %>% 
  select(where(is.numeric))

cor_matrix <- cor(numeric_data, use = "complete.obs") 
corrplot(cor_matrix, method = "circle")

```

---

###### 1.3 (5 points)

Split the data `df` into `df_train` and `df_split` using `test_ind` in the code below:

```R
set.seed(42)
test_ind <- sample(
  1:nrow(df), 
  floor( nrow(df)/10 ),
  replace=FALSE
)

df_train <- ... # Insert your code here
df_test  <- ... # Insert your code here
```
```{R}
set.seed(42)  
test_ind <- sample(
  1:nrow(df), 
  floor(nrow(df)/10),
  replace = FALSE
)

df_test <- df[test_ind, ]
df_train <- df[-test_ind, ]

```

---

###### 1.4 (5 points)

Fit a linear regression model to predict the `median_house_value` :

* `latitude`
* `longitude`
* `housing_median_age`
* `total_rooms`
* `total_bedrooms`
* `population`
* `median_income`
* `ocean_proximity`

Interpret the coefficients and summarize your results. 

```R
lm_fit <- ... # Insert your code here
... # Insert your code here
```
```{R}
lm_fit <- lm(median_house_value ~ latitude + longitude + housing_median_age + 
               total_rooms + total_bedrooms + population + 
               median_income + ocean_proximity, data = df_train)

summary_lm <- summary(lm_fit)

print(summary_lm)
```
The model explains about 64% of the variance in median house values (Multiple R-squared: 0.643). This indicates a relatively strong relationship between the predictors and the response variable. The model's F-statistic is significant, which means that the model performs significantly better than an intercept-only model.

---

###### 1.5 (5 points)

Complete the `rmse` function for computing the Root Mean-Squared Error between the true `y` and the predicted `yhat`, and use it to compute the RMSE for the regression model on `df_test`

```R
rmse <- function(y, yhat) {
  sqrt(mean((y - yhat)^2))
}

lm_predictions <- ... # Insert your code here
```
```{R}

rmse <- function(y, yhat) {
  sqrt(mean((y - yhat)^2))
}

lm_predictions <- predict(lm_fit, newdata = df_test)
lm_rmse <- rmse(df_test$median_house_value, lm_predictions)

print(lm_rmse)

```


###### 1.6 (5 points)

Fit a decision tree model to predict the `median_house_value` using the same predictors as in 1.4. Use the `rpart()` function.

```R
rpart_fit <- ... # Insert your code here
rpart_predictions <- ... # Insert your code here
```
```{R}
library(rpart)
library(rpart.plot)

rpart_fit <- rpart(median_house_value ~ latitude + longitude + housing_median_age + 
                     total_rooms + total_bedrooms + population + 
                     median_income + ocean_proximity, data = df_train)

rpart_predictions <- predict(rpart_fit, newdata = df_test, type = "vector")
```


Visualize the decision tree using the `rpart.plot()` function. 

```R
... # Insert your code here
```
```{R}
rpart.plot(rpart_fit)
```


Report the root mean squared error on the test set.

```R
rpart_predictions <- ... # Insert your code here
```
```{R}

rpart_rmse <- rmse(df_test$median_house_value, rpart_predictions)

print(rpart_rmse)

```

---

###### 1.7 (5 points)

Fit a support vector machine model to predict the `median_house_value` using the same predictors as in 1.4. Use the `svm()` function and use any kernel of your choice. Report the root mean squared error on the test set.

```R
svm_fit <- ... # Insert your code here
svm_predictions <- ... # Insert your code here
```
```{R}
library(e1071)

svm_fit <- svm(median_house_value ~ latitude + longitude + housing_median_age +
                 total_rooms + total_bedrooms + population +
                 median_income + ocean_proximity,
               data = df_train,
               kernel = "radial")

svm_predictions <- predict(svm_fit, newdata = df_test)
svm_rmse <- rmse(df_test$median_house_value, svm_predictions)

print(svm_rmse)

```

---

###### 1.8 (25 points)

Initialize a neural network model architecture:

```R
NNet <- nn_module(
    initialize = function(p, q1, q2, q3){
      ... # Insert your code here
    },
    forward = function(x){
      ... # Insert your code here
    }
)
```
```{R}
library(luz)

NNet <- nn_module(
  initialize = function(p, q1, q2, q3) {
    self$hidden1 <- nn_linear(p, q1)
    self$hidden2 <- nn_linear(q1, q2)
    self$hidden3 <- nn_linear(q2, q3)
    self$output <- nn_linear(q3, 1)
    self$activation <- nn_relu()
  },
  forward = function(x) {
    x %>%
      self$hidden1() %>% self$activation() %>%
      self$hidden2() %>% self$activation() %>%
      self$hidden3() %>% self$activation() %>%
      self$output()
  }
)

```

Fit a neural network model to predict the `median_house_value` using the same predictors as in 1.4. Use the `model.matrix` function to create the covariate matrix and `luz` package for fitting the network with $32, 16, 8$ nodes in each of the three hidden layers. 

```R
nnet_fit <- NNet %>% 
  setup(
    ... # Insert your code here
  ) %>%
  set_hparams(
    ... # Insert your code here
  ) %>%
  set_opt_params(
    ... # Insert your code here
  ) %>%
  fit(
    ... # Insert your code here
    dataloader_options = ... # Insert your code here
    verbose = FALSE # Change to TRUE while tuning. But, set to FALSE before submitting

  )
```
```{R}
x_train <- model.matrix(median_house_value ~ . - 1, data = df_train)
x_test <- model.matrix(median_house_value ~ . -1, data = df_test)


y_train <- matrix(df_train$median_house_value, ncol = 1)
y_test <- matrix(df_test$median_house_value, ncol = 1)

nnet_fit <- NNet %>% 
  setup(loss = nn_mse_loss(), optimizer = optim_adam) %>%
  set_hparams(p = ncol(x_train), q1 = 32, q2 = 16, q3 = 8) %>%
  set_opt_hparams(lr = 0.02) %>%
  fit(
    data = list(x_train, y_train),
    valid_data = list(x_test, y_test),
    epochs = 10, verbose = TRUE
  )

```

Plot the results of the training and validation loss and accuracy.

```R
... # Insert your code here
```
```{R}
plot(nnet_fit)
```


Report the root mean squared error on the test set.


```R
nnet_predictions <- ... # Insert your code here
```
```{R}
rmse <- function(y, yhat) {
  sqrt(mean((y - yhat)^2))
}

nnet_predictions <- predict(nnet_fit, x_test)
nnet_predictions <- as_array(nnet_predictions) 
nnet_rmse <- rmse(y_test, nnet_predictions)

print(nnet_rmse)

```

::: {.callout-warning}
Remember to use the `as_array()` function to convert the predictions to a vector of numbers before computing the RMSE with `rmse()`
:::

---

###### 1.9 (5 points)

Summarize your results in a table comparing the RMSE for the different models. Which model performed best? Why do you think that is?

```R
... # Insert your code here
```
```{R}
library(knitr)
model_comparisons <- data.frame(
  Model = c("Linear Regression", "Decision Tree", "SVM", "Neural Network"),
  RMSE = c(lm_rmse, rpart_rmse, svm_rmse, nnet_rmse)
)

model_comparisons <- model_comparisons[order(model_comparisons$RMSE),]

kable(model_comparisons, caption = "Comparison of Model Performance (RMSE)", align = 'l')

```



<br><br><br><br>
<br><br><br><br>
---

## Question 2
::: {.callout-tip}
## 50 points
Spam email classification
:::

The `data` folder contains the `spam.csv` dataset. This dataset contains features extracted from a collection of spam and non-spam emails. The objective is to classify the emails as spam or non-spam.

---

###### 2.1 (2.5 points)

Read the data file as a tibble in R. Preprocess the data such that:

1. the variables are of the right data type, e.g., categorical variables are encoded as factors
2. all column names to lower case for consistency
3. Any observations with missing values are dropped

```R
df2 <- ... # Insert your code here
```
```{R}
library(readr)
library(dplyr)
library(tidyr)

path2 <- "/Users/zhangjingchun/Desktop/spambase.csv"

df2 <- read_csv(path2) %>%
  rename_with(tolower) %>% 
  drop_na() 

print(head(df2))

print(table(df2$spam))


```

---

###### 2.2 (2.5 points)

Split the data `df` into `df_train` and `df_split` using `test_ind` in the code below:

```R
set.seed(42)
test_ind <- sample(
  1:nrow(df), 
  floor( nrow(df)/10 ),
  replace=FALSE
)

df_train <- ... # Insert your code here
df_test  <- ... # Insert your code here
```
```{R}
set.seed(42) 
test_ind2 <- sample(
  1:nrow(df2), 
  floor(nrow(df2) / 10),
  replace=FALSE
)

df2_train <- df2[-test_ind2, ] 
df2_test <- df2[test_ind2, ]

```


Complete the `overview` function which returns a data frame with the following columns: `accuracy`, `error`, `false positive rate`, `true positive rate`, between the true `true_class` and the predicted `pred_class` for any classification model.

```R
overview <- function(pred_class, true_class) {
  accuracy <- ... # Insert your code here
  error <- ... # Insert your code here
  true_positives <- ... # Insert your code here
  true_negatives <- ... # Insert your code here
  false_positives <- ... # Insert your code here
  false_negatives <- ... # Insert your code here
  true_positive_rate <- ... # Insert your code here
  false_positive_rate <- ...  # Insert your code here
  return(
    data.frame(
      accuracy = accuracy,
      error = error,
      true_positive_rate = true_positive_rate,
      false_positive_rate = false_positive_rate
    )
  )
}
```
```{R}
overview <- function(pred_class, true_class) {
  true_positives <- sum((pred_class == 1) & (true_class == 1))
  true_negatives <- sum((pred_class == 0) & (true_class == 0))
  false_positives <- sum((pred_class == 1) & (true_class == 0))
  false_negatives <- sum((pred_class == 0) & (true_class == 1))
  
  accuracy <- (true_positives + true_negatives) / length(true_class)
  error <- (false_positives + false_negatives) / length(true_class)
  true_positive_rate <- true_positives / (true_positives + false_negatives)
  false_positive_rate <- false_positives / (false_positives + true_negatives)
  
  return(
    data.frame(
      accuracy = accuracy,
      error = error,
      true_positive_rate = true_positive_rate,
      false_positive_rate = false_positive_rate
    )
  )
}
```

---

###### 2.3 (5 points)

Fit a logistic regression model to predict the `spam` variable using the remaining predictors. Report the prediction accuracy on the test set.

```R
glm_fit <- ... # Insert your code here
glm_classes <- ... # Insert your code here
```
```{R}
glm_fit <- glm(spam ~ ., data = df2_train, family = binomial)
probabilities <- predict(glm_fit, df2_test, type = "response")
glm_classes <- ifelse(probabilities > 0.5, 1, 0)

overview(glm_classes, df2_test$spam)
```

---

###### 2.4 (5 points)

Fit a decision tree model to predict the `spam` variable using the remaining predictors. Use the `rpart()` function and set the `method` argument to `"class"`. 

```R
rpart_classes <- ... # Insert your code here
```
```{R}
library(rpart)

rpart_fit2 <- rpart(spam ~ ., data = df2_train, method = "class")
rpart_classes2 <- predict(rpart_fit2, df2_test, type = "class")

```


Visualize the decision tree using the `rpart.plot()` function. 

```R
... # Insert your code here
```
```{R}
library(rpart.plot)

rpart.plot(rpart_fit2)

```

Report the prediction accuracy on the test set.

```R
rpart_classes <- ... # Insert your code here
```
```{R}
actual_classes2 <- as.factor(df2_test$spam) 
accuracy2 <- sum(rpart_classes2 == actual_classes2) / length(actual_classes2)

print(paste("Prediction accuracy on the test set:", accuracy2))

```
Ans: The accuracy of this test dataset is 87.8%.
---

###### 2.5 (5 points)

Fit a support vector machine model to predict the `spam` variable using the remaining predictors. Use the `svm()` function and use any kernel of your choice. Remember to set the `type` argument to `"C-classification"` **if you haven't** already converted `spam` to be of type `factor`.


```R
svm_fit <- ... # Insert your code here
```
```{R}
library(e1071)
df2_train$spam <- as.factor(df2_train$spam)
svm_fit2 <- svm(spam ~ ., data = df2_train, type = "C-classification", kernel = "radial")
```

Report the prediction accuracy on the test set.

```R
svm_classes <- ... # Insert your code here
```
```{R}
svm_classes2 <- predict(svm_fit2, newdata = df2_test)
actual_spam2 <- df2_test$spam
sum(svm_classes2 == actual_spam2) / nrow(df2_test)

```
Ans: The prediction accuracy on the test set is 92.39%.
---

###### 2.6 (25 points)

Using the same neural network architecture as in 1.9, fit a neural network model to predict the `spam` variable using the remaining predictors. 

::: {.callout-warning}
## Classification vs. Regression

Note that the neural network in **Q 1.9** was a regression model. You will need to modify the neural network architecture to be a classification model by changing the output layer to have a single node with a sigmoid activation function.
:::

Use the `model.matrix` function to create the covariate matrix and `luz` package for fitting the network with $32, 16, 8$ nodes in each of the three hidden layers. 

```R
nnet_fit <- NNet %>% 
  setup(
    ... # Insert your code here
  ) %>%
  set_hparams(
    ... # Insert your code here
  ) %>%
  set_opt_params(
    ... # Insert your code here
  ) %>%
  fit(
    ... # Insert your code here
    dataloader_options = ... # Insert your code here
    verbose = FALSE # Change to TRUE while tuning. But, set to FALSE before submitting

  )
```

```{R}
library(torch)
library(luz)

NNet_binary <- nn_module(
  initialize = function(p, q1, q2, q3) {
    self$net <- nn_sequential(
      nn_linear(p, q1), nn_relu(),
      nn_linear(q1, q2), nn_relu(),
      nn_linear(q2, q3), nn_relu(),
      nn_linear(q3, 1)
    )
    self$activation <- nn_sigmoid()
  },
  forward = function(x) {
    self$net(x) %>% self$activation()
  }
)

X_train2 <- model.matrix(~ . - spam, data = df2_train)
y_train2 <- as.matrix(as.numeric(df2_train$spam))

nnet_fit <- NNet_binary %>% 
  setup(
    loss = nn_cross_entropy_loss(),
    optimizer = optim_adam
  ) %>%
  set_hparams(
    p = ncol(X_train2),
    q1 = 32,
    q2 = 16,
    q3 = 8
  ) %>% 
  set_opt_hparams(lr = 0.01) %>%
  fit(
    list(X_train2, y_train2),
    epochs = 40,
    dataloader_options = list(batch_size = 64),
    verbose = FALSE, 
    valid_data = 0.2
  )

X_test2 <- model.matrix(~ . - spam, data = df2_test)
nnet_pred <- nnet_fit %>% predict(X_test2)
nnet_classes <- ifelse(nnet_pred > 0.5, 1, 0)
nnet_overview <- overview(nnet_classes, df2_test$spam)
nnet_overview

```

---

###### 2.7 (5 points)

Summarize your results in a table comparing the accuracy metrics for the different models. 

```R
... # Insert your code here
```

If you were to choose a model to classify spam emails, which model would you choose? Think about the context of the problem and the cost of false positives and false negatives.
```{R}
accuracy_logistic <- mean(glm_classes == df2_test$spam)
accuracy_decision_tree <- mean(rpart_classes2 == df2_test$spam)
accuracy_svm <- mean(svm_classes2 == df2_test$spam)
accuracy_neural_network <- mean(nnet_classes == as.numeric(df2_test$spam) - 1) 

results <- data.frame(
  Model = c("Logistic Regression", "Decision Tree", "SVM", "Neural Network"),
  Accuracy = c(accuracy_logistic, accuracy_decision_tree, accuracy_svm, accuracy_neural_network)
)

print(results)

```

Ans: I will choose logistic regression model.


<br><br><br><br>
<br><br><br><br>
---

## Question 3
::: {.callout-tip}
## 60 points

Three spirals classification

:::

To better illustrate the power of depth in neural networks, we will use a toy dataset called the "Three Spirals" data. This dataset consists of two intertwined spirals, making it challenging for shallow models to classify the data accurately. 

::: {.callout-warning}
## This is a multi-class classification problem
:::

The dataset can be generated using the provided R code below:

```{R}
generate_three_spirals <- function(){
  set.seed(42)
  n <- 500
  noise <- 0.2
  t <- (1:n) / n * 2 * pi
  x1 <- c(
      t * (sin(t) + rnorm(n, 0, noise)),
      t * (sin(t + 2 * pi/3) + rnorm(n, 0, noise)),
      t * (sin(t + 4 * pi/3) + rnorm(n, 0, noise))
    )
  x2 <- c(
      t * (cos(t) + rnorm(n, 0, noise)),
      t * (cos(t + 2 * pi/3) + rnorm(n, 0, noise)),
      t * (cos(t + 4 * pi/3) + rnorm(n, 0, noise))
    )
  y <- as.factor(
    c(
      rep(0, n), 
      rep(1, n), 
      rep(2, n)
    )
  )
  return(tibble::tibble(x1=x1, x2=x2, y=y))
}
```

---

###### 3.1 (5 points)

Generate the three spirals dataset using the code above. Plot $x_1$ vs $x_2$ and use the `y` variable to color the points. 


```{R}
df3 <- generate_three_spirals()

plot(
  df3$x1, df3$x2,
  col = df3$y,
  pch = 20
)
```

Define a grid of $100$ points from $-10$ to $10$ in both $x_1$ and $x_2$ using the `expand.grid()`. Save it as a tibble called `df_test`. 

```R
grid <- ... # Insert your code here
df_test <- ... # Insert your code here
```
```{R}
grid <- expand.grid(x1 = seq(-10, 10, length.out = 100),
                    x2 = seq(-10, 10, length.out = 100))

df3_test <- tibble::as_tibble(grid)

```

---

###### 3.2 (10 points)

Fit a classification tree model to predict the `y` variable using the `x1` and `x2` predictors, and plot the decision boundary. 

```R
rpart_fit <- ... # Insert your code here
rpart_classes <- ... # Insert your code here
```
```{R}
if (!require('rpart')) install.packages('rpart')
library(rpart)

rpart_fit3 <- rpart(y ~ x1 + x2, data = df3, method = "class")

rpart_classes3 <- predict(rpart_fit3, newdata = df3_test, type = "class")

```

Plot the decision boundary using the following function:

```R
plot_decision_boundary <- function(predictions){
  plot(
    df_test$x1, df_test$x2, 
    col = predictions,
    pch = 0
  )
  points(
    df$x1, df$x2,
    col = df$y,
    pch = 20
  )
}
```
```{R}
plot_decision_boundary <- function(predictions, df3, df3_test){
  plot(
    df3_test$x1, df3_test$x2, 
    col = as.numeric(predictions) + 1, 
    pch = 20,
    xlab = "x1",
    ylab = "x2",
    main = "Decision Boundary of Classification Tree"
  )
  points(
    df3$x1, df3$x2,
    col = as.numeric(df3$y) + 1,
    pch = 20
  )
}


```

```R
plot_decision_boundary(rpart_classes)
```
```{R}
plot_decision_boundary(rpart_classes3, df3, df3_test)
```

---

###### 3.3 (10 points)

Fit a support vector machine model to predict the `y` variable using the `x1` and `x2` predictors. Use the `svm()` function and use any kernel of your choice. Remember to set the `type` argument to `"C-classification"` **if you haven't** converted `y` to be of type `factor`.

```R
svm_fit <- ... # Insert your code here
svm_classes <- ... # Insert your code here
plot_decision_boundary(svm_classes)
```
```{R}
if (!require('e1071')) install.packages('e1071')
library(e1071)

svm_fit3 <- svm(y ~ x1 + x2, data = df3, type = "C-classification", kernel = "radial")

svm_classes3 <- predict(svm_fit3, newdata = df3_test)

plot_decision_boundary(svm_classes3, df3, df3_test)

```

---

::: {.callout-warning}
## Instructions

For the next questions, you will need to fit a series of neural networks. In all cases, you can:

* set the number of units in each hidden layer to 10 
* set the output dimension `o` to 3 (remember this is multinomial classification)
* use the appropriate loss function for the problem (**not `nn_bce_loss`**)
* set the number of epochs to $50$
* fit the model using the `luz` package

You can use any optimizer of your choice, but you **will need to tune the learning rate for each problem**.
:::


###### 3.4 (10 points)

Fit a neural network with **1 hidden layer** to predict the `y` variable using the `x1` and `x2` predictors.

```R
NN1 <- nn_module(
  initialize = function(p, q1, o){
    self$hidden1 <- ... # Insert your code here
    self$output <- ... # Insert your code here
    self$activation <- ... # Insert your code here
  },
  forward = function(x){
    x %>% 
      self$hidden1() %>% 
      self$activation() %>% 
      self$output()
  }
)

fit_1 <- NN1 %>% 
  setup(
    ... # Insert your code here
  ) %>%
  set_hparams(
    ... # Insert your code here
  ) %>%
  set_opt_params(
    ... # Insert your code here
  ) %>%
  fit(
    data = list(
      df %>% select(x1, x2) %>% as.matrix,
      df$y %>% as.integer
    ),
    ... # Insert your code here
    dataloader_options = ... # Insert your code here
    verbose = FALSE
  )
```

In order to generate the class predictions, you will need to use the `predict()` function as follows

```R
test_matrix <- df_test %>% select(x1, x2) %>% as.matrix

fit_1_predictions <- predict(fit_1, test_matrix) %>% 
  argmax(2) %>% 
  as.integer()
```
```{R}
library(torch)
library(luz)


# Define the neural network module
NN1 <- nn_module(
  initialize = function(p, q1, o) {
    self$hidden1 <- nn_linear(p, q1) 
    self$output <- nn_linear(q1, o) 
    self$activation <- nn_relu() 
  },
  forward = function(x) {
    x %>%
      self$hidden1() %>%
      self$activation() %>%
      self$output()
  }
)

p <- 2 
q1 <- 5
o <- 3 


```

```R
fit_1 <- NN1 %>%
  setup(
    loss = nn_cross_entropy_loss(),
    optimizer = optim_adam 
  ) %>%
  set_hparams(
    p = p,
    q1 = q1,
    o = o
  ) %>%
  set_opt_hparams(
    lr = 0.01
  ) %>%
  fit(
    data = list(
      x = df3 %>% select(x1, x2) %>% as.matrix(),
      y = df3$y %>% as.integer()
    ),
    epochs = 50,
    dataloader_options = list(batch_size = 64),
    valid_data = 0.2,
    verbose = TRUE
  )

```

Plot the results using the `plot_decision_boundary()` function.
```R
test_matrix <- df_test %>% 
  select(x1, x2) %>% 
  as.matrix()

fit_1_predictions <- predict(fit_1, test_matrix) %>%
  torch::argmax(dim = 2) %>%
  as.integer() %>%
  torch::as_array()

plot_decision_boundary <- function(predictions, df, df_test){
  plot(
    df_test$x1, df_test$x2, 
    col = predictions, # Use the predictions to color the grid
    pch = 20,
    xlab = "x1",
    ylab = "x2",
    main = "Decision Boundary of Neural Network"
  )
  points(
    df$x1, df$x2,
    col = as.numeric(df$y) + 1, # Color the original points for comparison
    pch = 20
  )
}

# Call the function with the predictions
plot_decision_boundary(fit_1_predictions, df3, df_test)
```

---

###### 3.5 (10 points)

Fit a neural network with **0 hidden layers** to predict the `y` variable using the `x1` and `x2` predictors.

```{R}
library(torch)
library(luz)
library(dplyr)

NN0 <- nn_module(
  initialize = function(p, o) {
    self$output <- nn_linear(in_features = p, out_features = o, bias = TRUE)
  },
  forward = function(x) {
    x %>% self$output()
  }
)

```

```R
p <- 2 # Number of features (x1, x2)
o <- 3 # Number of output classes
df3$y <- df3$y + 1

fit_0 <- NN0 %>%
  setup(
    loss = nn_cross_entropy_loss(),
    optimizer = optim_adam
  ) %>%
  set_hparams(
    p = p,
    o = o
  ) %>%
  set_opt_hparams(
    lr = 0.01 # Set the learning rate
  ) %>%
  fit(
    data = list(
      x = df3 %>% select(x1, x2) %>% as.matrix(),
      y = df3$y %>% as.integer() # No need to subtract 1 now
    ),
    epochs = 50,
    dataloader_options = list(batch_size = 64),
    valid_data = 0.2,
    verbose = TRUE
  )

```


Plot the results using the `plot_decision_boundary()` function.
```R
plot_decision_boundary(fit_1_predictions, df3, df_test)
```
```R

test_matrix <- df3_test3%>% select(x1, x2) %>% as.matrix()

fit_0_predictions <- predict(fit_0, test_matrix) %>%
  torch::argmax(dim = 2) %>%
  as.integer() %>%
  torch::as_array()

plot_decision_boundary <- function(predictions, df3, df3_test) {
  plot(
    df3_test$x1, df3_test$x2,
    col = predictions, 
    pch = 20,
    xlab = "x1", ylab = "x2",
    main = 
  )
  
  points(
    df3$x1, df3$x2,
    col = as.numeric(df3$y) + 1, 
    pch = 4 # 
  )
}

plot_decision_boundary(fit_0_predictions, df3, df3_test)

```



---


###### 3.6 (10 points)

Fit a neural network with **3 hidden layers** to predict the `y` variable using the `x1` and `x2` predictors.

```R
NN2 <- nn_module(
  initialize = function(p, q1, q2, o){
    ... # Insert your code here
  },
  forward = function(x){
    x %>% 
    ... # Insert your code here
  }
)

fit_2 <- NN3 %>% 
  setup(...) %>%
  set_hparams(...) %>%
  set_opt_params(...) %>%
  fit(...)
```
```{R}
library(torch)
library(luz)
library(dplyr)

NN2 <- nn_module(
  initialize = function(p, q1, q2, q3, o) {
    self$hidden1 <- nn_linear(p, q1)
    self$hidden2 <- nn_linear(q1, q2)
    self$hidden3 <- nn_linear(q2, q3)
    self$output <- nn_linear(q3, o)
    self$activation <- nn_relu()
  },
  forward = function(x) {
    x %>%
      self$hidden1() %>%
      self$activation() %>%
      self$hidden2() %>%
      self$activation() %>%
      self$hidden3() %>%
      self$activation() %>%
      self$output()
  }
)
```

```R
fit_2 <- NN2 %>%
  setup(
    loss = nn_cross_entropy_loss(), 
    optimizer = optim_adam
  ) %>%
  set_hparams(
    p = 2, 
    q1 = 10, 
    q2 = 10, 
    q3 = 10, 
    o = 3 
  ) %>%
  set_opt_hparams(
    lr = 0.01 
  ) %>%
  fit(
    data = list(
      x = df3 %>% select(x1, x2) %>% as.matrix(),
      y = df3$y %>% as.integer() 
    ),
    epochs = 50,
    dataloader_options = list(batch_size = 64),
    valid_data = 0.2,
    verbose = TRUE
  )

```


Plot the results using the `plot_decision_boundary()` function.

```R
test_matrix <- df_test %>% select(x1, x2) %>% as.matrix()

predictions <- predict(fit_2, test_matrix) %>%
  torch::argmax(dim = 2) %>%
  as.integer() %>%
  torch::as_array()

plot_decision_boundary(predictions, df3, df_test)
```

---

###### 3.7 (5 points)

What are the differences between the models? How do the decision boundaries change as the number of hidden layers increases?
Ans:
As the number of hidden layers increases, a neural network's capacity to model complex relationships and patterns in the data also increases. This is reflected in the decision boundaries it learns: moving from simple, linear boundaries with no hidden layers, to highly complex, non-linear boundaries with multiple hidden layers. 

---


:::{.hidden unless-format="pdf"}
\pagebreak
:::

<br><br><br><br>
<br><br><br><br>
---



::: {.callout-note collapse="true"}
## Session Information

Print your `R` session information using the following command

```{R}
sessionInfo()
```